[package]
name = "rust-and-ts-test"
version = "0.1.0"
description = "Tests for the rust_and_ts generated code"
edition = "2021"
rust-version = "1.81"

[dependencies]
rust-and-ts = { path = "../../output/rust" }
anyhow = "1.0.95"
apache-avro = { git = "https://github.com/apache/avro-rs.git" }
serde_bytes = "0.11.19"
rust_decimal = "1.39.0"
bigdecimal = "0.4.9"
